appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bDCQi6c2jW5LrRIJ69Yu90+FmosBHy2+qes5DssQTDJjRVK72dtmzxJmdLbmVg7Bk60wpnmpQfLqylRI+K2CBFQ92sG0B8oTv42bhaVbta1nPGddK5Ddusr10f4WHs2lTi+Kp9XExrTGDiH9edgTHsGr12rjSDXNDi21XSq5erghbBXbzphEqXftiDeFzjmCl3Ti/dVd8RMuNLlxoAkxcuQLs7zfHbd+v+3gNtEB/g8A0OIHz6NHAjyQp/VaB9nOHY86EbGzTri5UaE3yxsUAPLLxBPGlRgO/w9zNggdDi9/NTngY0kdvnrWsgEWIAr/qP6kSgAh5O/Av/xE+fkYIXi7La4rsH+7fd/BYbY5vn6I/vFl+UY3PpIQnS0UjOnCGy3G4QE4ej2qG4P3OLqiEnJtnCp7rdIl26sM01vsJuFPXm/KuOIYvkJPGDvbtAkN7H/I8nK6VIWh7/KlIbwe/rd+y1VfzwDL12ZmeEWU2i2TyDZORp6i3HxoZEkv+FyEL39/aq39c2EdLUwGdKT9aEXXKgF4Md4jOj4CMehCzEpHOorhieukVTRKQ0/iuCzGyCiiVTOp/hRn8dEgrcnpeCtnQ8c2ce7w9S3N7nXcelK8ur6LfAM11wwbQZ6N++MlBFyxM8YfvimWJvUx6b31go+UWMZcm1vzy/2ukXtcJbg=}
